"use client";

import { FormEvent, useEffect, useState } from "react";
import { History, Search, ShieldCheck, Trash2 } from "lucide-react";
import { FeatureHeader } from "@/components/features/shared";
import { useLanguage } from "@/components/language-provider";
import { featureCopy } from "@/lib/features-i18n";

type Site = { id: string; name: string; latitude: number; longitude: number; description?: string | null; source: string; externalId?: string | null; reviewCount: number };
type Log = { id: string; action: string; createdAt: string; actor?: { username: string } | null; site?: { name: string } | null; before?: unknown; after?: unknown };

export function AdminSitesFeature() {
  const { locale } = useLanguage(); const c = featureCopy(locale); const [sites, setSites] = useState<Site[]>([]); const [logs, setLogs] = useState<Log[]>([]); const [query, setQuery] = useState(""); const [mergeTargets, setMergeTargets] = useState<Record<string, string>>({}); const [message, setMessage] = useState("");
  async function load(q = query) { const response = await fetch(`/api/admin/sites?q=${encodeURIComponent(q)}`); if (response.ok) { const data = await response.json(); setSites(data.sites); setLogs(data.logs); } }
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(async () => { const response = await fetch("/api/admin/sites?q=", { signal: controller.signal }); if (response.ok) { const data = await response.json(); setSites(data.sites); setLogs(data.logs); } }, 0); return () => { controller.abort(); window.clearTimeout(timer); }; }, []);
  async function update(event: FormEvent<HTMLFormElement>, site: Site) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch(`/api/admin/sites/${site.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), latitude: Number(form.get("latitude")), longitude: Number(form.get("longitude")), description: form.get("description") }) }); setMessage(response.ok ? c.saved : c.genericError); if (response.ok) await load(); }
  async function merge(site: Site) { const targetId = mergeTargets[site.id]?.trim(); if (!targetId || !window.confirm(`${c.merge}: ${site.name}?`)) return; const response = await fetch("/api/admin/sites/merge", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ duplicateId: site.id, targetId }) }); setMessage(response.ok ? c.saved : c.genericError); if (response.ok) await load(); }
  async function remove(site: Site) { if (!window.confirm(`${c.deleteSite}: ${site.name}?`)) return; const response = await fetch(`/api/admin/sites/${site.id}`, { method: "DELETE" }); setMessage(response.ok ? c.saved : response.status === 409 ? "Site has reviews: merge it instead." : c.genericError); if (response.ok) await load(); }
  return <div className="feature-page admin-sites-page"><FeatureHeader eyebrow="BLUEMATES CONTROL" title={c.adminTitle} subtitle={c.adminSub} action={<ShieldCheck size={28} />} /><form className="admin-site-search" onSubmit={(event) => { event.preventDefault(); void load(); }}><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={c.searchPlace} /><button>{c.searchDivers}</button></form>{message && <p className="success-banner">{message}</p>}<div className="admin-sites-grid"><section className="admin-site-list">{sites.map((site) => <form onSubmit={(event) => update(event, site)} className="admin-site-card" key={site.id}><header><code>{site.id}</code><span>{site.source} · {site.reviewCount} {c.reviewCount.toLowerCase()}</span></header><input name="name" defaultValue={site.name} required /><div className="compact-row"><input name="latitude" type="number" step="any" defaultValue={site.latitude} required /><input name="longitude" type="number" step="any" defaultValue={site.longitude} required /></div><textarea name="description" defaultValue={site.description || ""} rows={3} /><div className="admin-site-actions"><button>{c.updateSite}</button><input value={mergeTargets[site.id] || ""} onChange={(event) => setMergeTargets((current) => ({ ...current, [site.id]: event.target.value }))} placeholder={c.mergeInto} /><button type="button" onClick={() => merge(site)}>{c.merge}</button><button type="button" className="danger-action" onClick={() => remove(site)}><Trash2 size={14} />{c.deleteSite}</button></div></form>)}</section><aside className="audit-panel"><h2><History size={18} />{c.auditLog}</h2>{logs.map((log) => <article key={log.id}><strong>{log.action.replaceAll("_", " ")}</strong><span>{log.site?.name || "—"} · @{log.actor?.username || "system"}</span><small>{new Date(log.createdAt).toLocaleString(locale)}</small><details><summary>JSON</summary><pre>{JSON.stringify({ before: log.before, after: log.after }, null, 2)}</pre></details></article>)}</aside></div></div>;
}
