"use client";

import { FormEvent, useState } from "react";
import { BadgeCheck, Fingerprint } from "lucide-react";
import { useLanguage } from "@/components/language-provider";
import { featureCopy } from "@/lib/features-i18n";
import { FeatureHeader, PhotoUploader, VisibilitySelect } from "@/components/features/shared";

type ProfileUser = { publicId: string; firstName: string; lastName: string; username: string; birthDate?: string | Date | null; bio?: string | null; avatarUrl?: string | null; profileVisibility: "PUBLIC" | "PRIVATE"; logbookVisibility: "PUBLIC" | "PRIVATE" };

export function ProfileSettingsFeature({ user }: { user: ProfileUser }) {
  const { locale, t } = useLanguage(); const c = featureCopy(locale); const [profileVisibility, setProfileVisibility] = useState(user.profileVisibility); const [logbookVisibility, setLogbookVisibility] = useState(user.logbookVisibility); const [avatarMediaId, setAvatarMediaId] = useState<string | null>(null); const [pending, setPending] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ firstName: form.get("firstName"), lastName: form.get("lastName"), username: form.get("username"), birthDate: form.get("birthDate") || null, bio: form.get("bio"), profileVisibility, logbookVisibility, avatarMediaId }) }); const result = await response.json(); setMessage(response.ok ? c.profileSaved : result.error === "USERNAME_TAKEN" ? t.usernameTaken : c.genericError); setPending(false); }
  const birth = user.birthDate ? new Date(user.birthDate).toISOString().slice(0, 10) : "";
  return <div className="feature-page"><FeatureHeader eyebrow="DIVER IDENTITY" title={c.profileTitle} subtitle={c.profileSub} /><div className="profile-settings-grid"><aside className="identity-pass"><div className="profile-photo-large">{user.avatarUrl ? <img src={user.avatarUrl} alt="" /> : <span>{user.firstName[0]}{user.lastName[0]}</span>}</div><BadgeCheck size={20} /><strong>@{user.username}</strong><small>{c.memberId}</small><code>{user.publicId}</code><p><Fingerprint size={15} />{c.immutableId}</p></aside><form className="feature-form profile-form" onSubmit={submit}><div className="form-grid"><label>{c.firstName}<input name="firstName" defaultValue={user.firstName} required maxLength={60} /></label><label>{c.lastName}<input name="lastName" defaultValue={user.lastName} required maxLength={60} /></label><label>{c.username}<input name="username" defaultValue={user.username} required minLength={3} maxLength={30} pattern="[a-zA-Z0-9._-]+" /></label><label>{c.birthDate}<input name="birthDate" type="date" defaultValue={birth} max={new Date().toISOString().slice(0, 10)} /></label></div><label>{c.bio}<textarea name="bio" rows={5} defaultValue={user.bio ?? ""} maxLength={500} /></label><div><span className="section-label">{c.profilePhoto}</span><PhotoUploader kind="AVATAR" multiple={false} onChange={(ids) => setAvatarMediaId(ids[0] ?? null)} /></div><div className="privacy-settings"><div><span>{c.profilePrivacy}</span><VisibilitySelect value={profileVisibility} onChange={setProfileVisibility} /></div><div><span>{c.logbookPrivacy}</span><VisibilitySelect value={logbookVisibility} onChange={setLogbookVisibility} /></div></div><p className="privacy-help">{c.visibilityHelp}</p>{message && <p className={message === c.profileSaved ? "success-banner" : "form-error"}>{message}</p>}<button className="primary-action" disabled={pending}>{pending ? c.saving : c.saveProfile}</button></form></div></div>;
}
