import type { Locale } from "@/lib/i18n";

const copy = {
  en: {
    navHome: "Overview", navLogbook: "Logbook", navFriends: "Friends", navMap: "World map", navPlanning: "Planning", navReviews: "Site reviews", navProfile: "Edit profile",
    logbookTitle: "My digital logbook", logbookSub: "Keep every dive, detail and memory in one place.", addDive: "Log a dive", logbookPrivacy: "Logbook visibility", divePrivacy: "This dive", public: "Public", private: "Private", site: "Dive site", date: "Date", depth: "Maximum depth (m)", duration: "Duration (minutes)", details: "Dive notes", coordinates: "Location", latitude: "Latitude", longitude: "Longitude", useLocation: "Use my location", photos: "Photos", choosePhotos: "Choose photos", saveDive: "Save dive", noDives: "No dives logged yet.", meters: "m", minutes: "min",
    friendsTitle: "Dive connections", friendsSub: "Find divers by username or member ID.", searchDivers: "Search divers", searchPlaceholder: "Username or member ID…", pendingRequests: "Pending requests", myFriends: "My friends", sentRequests: "Sent requests", connect: "Connect", requestSent: "Request sent", accept: "Accept", decline: "Decline", friends: "Friends", viewProfile: "View profile", noRequests: "No pending requests.", noFriends: "Your dive circle starts here.", privateDiver: "Private diver",
    mapTitle: "Our diving world", mapSub: "Your dives, your friends’ public dives, future trips and site reviews.", completedDive: "Completed dive", futureDive: "Future dive", siteReview: "Site review", mapHint: "Drag to explore, scroll or use controls to zoom, and switch globe mode with the control.", loadingMap: "Loading the ocean…",
    planningTitle: "Plan the next descent", planningSub: "Schedule future dives and decide who can see each plan.", addPlan: "Plan a dive", plannedFor: "Date and time", savePlan: "Save plan", noPlans: "No future dives planned.", future: "Future",
    reviewsTitle: "Rate a dive site", reviewsSub: "Pin a GPS location, share photos and help other divers choose.", rating: "Rating", comment: "Review", publishReview: "Publish review", noReviews: "You have not reviewed a site yet.", stars: "stars",
    profileTitle: "Your diver profile", profileSub: "Control your public identity and logbook privacy.", firstName: "First name", lastName: "Last name", username: "Username", birthDate: "Date of birth", age: "Age", bio: "Bio", profilePhoto: "Profile photo", profilePrivacy: "Profile visibility", saveProfile: "Save profile", memberId: "Member ID", immutableId: "This member ID stays the same when you edit your name.", profileSaved: "Profile updated.", publicProfile: "Public profile", hiddenProfile: "This diver keeps their profile private.", dives: "Dives", upcoming: "Upcoming dives", reviews: "Reviews", joined: "Joined", connectionPending: "Connection pending", incomingConnection: "Reply from the Friends tab", alreadyConnected: "Connected", backDashboard: "Back to dashboard",
    required: "Please complete the required fields.", uploadError: "A photo could not be uploaded.", genericError: "Something went wrong. Please try again.", saved: "Saved", saving: "Saving…", loading: "Loading…", visibilityHelp: "Public content can be seen by signed-in divers. Private content is only visible to you.", maxPhotos: "JPEG, PNG or WebP · 5 MB max each · up to 6", locationDenied: "Location access was unavailable.", clickMapInfo: "Search for a dive site, city, landmark or address.", logout: "Sign out", searchPlace: "Search for a place", searchPlaceHelp: "Type a site, reef, city, restaurant or address", searchingPlaces: "Searching places…", noPlaceFound: "No matching place found.", selectedLocation: "Selected location", manualCoordinates: "Enter coordinates manually", geocodingCredit: "Search data © OpenStreetMap contributors · Photon", footerTagline: "Your diving life, everywhere.", mobileApps: "Mobile applications", iosApp: "Download on iOS", androidApp: "Get it on Android", comingSoon: "Coming soon", footerRights: "All rights reserved.", deleteDive: "Delete dive", deleteDiveConfirm: "Delete this logbook entry and its photos?", groupDive: "Group dives", groupSize: "Number of identical dives", clickDiveActions: "Click or right-click an entry to group or delete it.", mapFilters: "Map display filters", startDate: "Start date", endDate: "End date", invalidDateRange: "Choose a valid date range beginning today or later.", profileDiveMap: "Dive map", profileDiveMapSub: "Places where this diver has explored the underwater world.", noMappedDives: "No geolocated public dives yet.", clickReviewDetails: "Click a review to see its map and photos.", reviewDetails: "Site position and photos", close: "Close", friendActivity: "Friends’ dives and plans",
  },
  fr: {
    navHome: "Aperçu", navLogbook: "Carnet", navFriends: "Amis", navMap: "Carte mondiale", navPlanning: "Planification", navReviews: "Avis sites", navProfile: "Modifier le profil",
    logbookTitle: "Mon carnet numérique", logbookSub: "Conservez chaque plongée, détail et souvenir au même endroit.", addDive: "Ajouter une plongée", logbookPrivacy: "Visibilité du carnet", divePrivacy: "Cette plongée", public: "Public", private: "Privé", site: "Site de plongée", date: "Date", depth: "Profondeur maximale (m)", duration: "Durée (minutes)", details: "Notes de plongée", coordinates: "Localisation", latitude: "Latitude", longitude: "Longitude", useLocation: "Utiliser ma position", photos: "Photos", choosePhotos: "Choisir des photos", saveDive: "Enregistrer", noDives: "Aucune plongée enregistrée.", meters: "m", minutes: "min",
    friendsTitle: "Connexions de plongée", friendsSub: "Trouvez des plongeurs par pseudo ou identifiant membre.", searchDivers: "Rechercher", searchPlaceholder: "Pseudo ou identifiant membre…", pendingRequests: "Demandes en attente", myFriends: "Mes amis", sentRequests: "Demandes envoyées", connect: "Se connecter", requestSent: "Demande envoyée", accept: "Accepter", decline: "Refuser", friends: "Amis", viewProfile: "Voir le profil", noRequests: "Aucune demande en attente.", noFriends: "Votre cercle de plongée commence ici.", privateDiver: "Plongeur privé",
    mapTitle: "Notre monde sous-marin", mapSub: "Vos plongées, celles publiques de vos amis, les projets et les avis.", completedDive: "Plongée réalisée", futureDive: "Plongée future", siteReview: "Avis de site", mapHint: "Faites glisser pour explorer, zoomez avec la molette ou les contrôles, et activez le globe via le contrôle.", loadingMap: "Chargement de l’océan…",
    planningTitle: "Planifier la prochaine descente", planningSub: "Programmez vos plongées et choisissez qui peut voir chaque projet.", addPlan: "Planifier une plongée", plannedFor: "Date et heure", savePlan: "Enregistrer le projet", noPlans: "Aucune plongée future planifiée.", future: "À venir",
    reviewsTitle: "Noter un site de plongée", reviewsSub: "Placez un point GPS, partagez des photos et aidez les autres plongeurs.", rating: "Note", comment: "Avis", publishReview: "Publier l’avis", noReviews: "Vous n’avez pas encore noté de site.", stars: "étoiles",
    profileTitle: "Votre profil plongeur", profileSub: "Contrôlez votre identité publique et la confidentialité du carnet.", firstName: "Prénom", lastName: "Nom", username: "Pseudo", birthDate: "Date de naissance", age: "Âge", bio: "Biographie", profilePhoto: "Photo de profil", profilePrivacy: "Visibilité du profil", saveProfile: "Enregistrer le profil", memberId: "Identifiant membre", immutableId: "Cet identifiant ne change pas lorsque vous modifiez votre nom.", profileSaved: "Profil mis à jour.", publicProfile: "Profil public", hiddenProfile: "Ce plongeur garde son profil privé.", dives: "Plongées", upcoming: "Plongées à venir", reviews: "Avis", joined: "Inscrit", connectionPending: "Demande en attente", incomingConnection: "Répondez depuis l’onglet Amis", alreadyConnected: "Connecté", backDashboard: "Retour au tableau de bord",
    required: "Veuillez compléter les champs obligatoires.", uploadError: "Une photo n’a pas pu être envoyée.", genericError: "Une erreur est survenue. Réessayez.", saved: "Enregistré", saving: "Enregistrement…", loading: "Chargement…", visibilityHelp: "Le contenu public est visible des plongeurs connectés. Le contenu privé n’est visible que par vous.", maxPhotos: "JPEG, PNG ou WebP · 5 Mo max · jusqu’à 6", locationDenied: "La localisation n’est pas disponible.", clickMapInfo: "Recherchez un site, une ville, un point de repère ou une adresse.", logout: "Se déconnecter", searchPlace: "Rechercher un lieu", searchPlaceHelp: "Saisissez un site, récif, ville, restaurant ou adresse", searchingPlaces: "Recherche des lieux…", noPlaceFound: "Aucun lieu correspondant.", selectedLocation: "Lieu sélectionné", manualCoordinates: "Saisir les coordonnées manuellement", geocodingCredit: "Données de recherche © contributeurs OpenStreetMap · Photon", footerTagline: "Votre vie de plongeur, partout.", mobileApps: "Applications mobiles", iosApp: "Télécharger sur iOS", androidApp: "Disponible sur Android", comingSoon: "Bientôt disponible", footerRights: "Tous droits réservés.", deleteDive: "Supprimer la plongée", deleteDiveConfirm: "Supprimer cette entrée du carnet et ses photos ?", groupDive: "Grouper les plongées", groupSize: "Nombre de plongées identiques", clickDiveActions: "Cliquez ou faites un clic droit sur une entrée pour la grouper ou la supprimer.", mapFilters: "Filtres d’affichage de la carte", startDate: "Date de début", endDate: "Date de fin", invalidDateRange: "Choisissez une période valide commençant aujourd’hui ou plus tard.", profileDiveMap: "Carte des plongées", profileDiveMapSub: "Les endroits où ce plongeur a exploré le monde sous-marin.", noMappedDives: "Aucune plongée publique géolocalisée.", clickReviewDetails: "Cliquez sur un avis pour afficher sa carte et ses photos.", reviewDetails: "Position et photos du site", close: "Fermer", friendActivity: "Plongées et projets des amis",
  },
  es: {
    navHome: "Resumen", navLogbook: "Diario", navFriends: "Amigos", navMap: "Mapa mundial", navPlanning: "Planificación", navReviews: "Reseñas", navProfile: "Editar perfil",
    logbookTitle: "Mi diario digital", logbookSub: "Guarda cada inmersión, detalle y recuerdo en un solo lugar.", addDive: "Añadir inmersión", logbookPrivacy: "Visibilidad del diario", divePrivacy: "Esta inmersión", public: "Público", private: "Privado", site: "Sitio de buceo", date: "Fecha", depth: "Profundidad máxima (m)", duration: "Duración (minutos)", details: "Notas de inmersión", coordinates: "Ubicación", latitude: "Latitud", longitude: "Longitud", useLocation: "Usar mi ubicación", photos: "Fotos", choosePhotos: "Elegir fotos", saveDive: "Guardar inmersión", noDives: "Aún no hay inmersiones.", meters: "m", minutes: "min",
    friendsTitle: "Conexiones de buceo", friendsSub: "Encuentra buceadores por usuario o ID de miembro.", searchDivers: "Buscar buceadores", searchPlaceholder: "Usuario o ID de miembro…", pendingRequests: "Solicitudes pendientes", myFriends: "Mis amigos", sentRequests: "Solicitudes enviadas", connect: "Conectar", requestSent: "Solicitud enviada", accept: "Aceptar", decline: "Rechazar", friends: "Amigos", viewProfile: "Ver perfil", noRequests: "No hay solicitudes pendientes.", noFriends: "Tu círculo de buceo comienza aquí.", privateDiver: "Buceador privado",
    mapTitle: "Nuestro mundo submarino", mapSub: "Tus inmersiones, las públicas de amigos, futuros viajes y reseñas.", completedDive: "Inmersión realizada", futureDive: "Inmersión futura", siteReview: "Reseña del sitio", mapHint: "Arrastra para explorar, usa la rueda o los controles para ampliar y activa el globo con el control.", loadingMap: "Cargando el océano…",
    planningTitle: "Planifica el próximo descenso", planningSub: "Programa inmersiones y decide quién puede ver cada plan.", addPlan: "Planificar inmersión", plannedFor: "Fecha y hora", savePlan: "Guardar plan", noPlans: "No hay inmersiones futuras.", future: "Futura",
    reviewsTitle: "Valora un sitio de buceo", reviewsSub: "Marca una ubicación GPS, comparte fotos y ayuda a otros buceadores.", rating: "Valoración", comment: "Reseña", publishReview: "Publicar reseña", noReviews: "Todavía no has valorado ningún sitio.", stars: "estrellas",
    profileTitle: "Tu perfil de buceo", profileSub: "Controla tu identidad pública y la privacidad del diario.", firstName: "Nombre", lastName: "Apellido", username: "Usuario", birthDate: "Fecha de nacimiento", age: "Edad", bio: "Biografía", profilePhoto: "Foto de perfil", profilePrivacy: "Visibilidad del perfil", saveProfile: "Guardar perfil", memberId: "ID de miembro", immutableId: "Este ID no cambia cuando editas tu nombre.", profileSaved: "Perfil actualizado.", publicProfile: "Perfil público", hiddenProfile: "Este buceador mantiene su perfil privado.", dives: "Inmersiones", upcoming: "Próximas inmersiones", reviews: "Reseñas", joined: "Miembro desde", connectionPending: "Solicitud pendiente", incomingConnection: "Responde desde la pestaña Amigos", alreadyConnected: "Conectado", backDashboard: "Volver al panel",
    required: "Completa los campos obligatorios.", uploadError: "No se pudo subir una foto.", genericError: "Algo salió mal. Inténtalo de nuevo.", saved: "Guardado", saving: "Guardando…", loading: "Cargando…", visibilityHelp: "El contenido público es visible para buceadores conectados. El privado solo para ti.", maxPhotos: "JPEG, PNG o WebP · 5 MB máx. · hasta 6", locationDenied: "La ubicación no está disponible.", clickMapInfo: "Busca un sitio, ciudad, punto de referencia o dirección.", logout: "Cerrar sesión", searchPlace: "Buscar un lugar", searchPlaceHelp: "Escribe un sitio, arrecife, ciudad, restaurante o dirección", searchingPlaces: "Buscando lugares…", noPlaceFound: "No se encontró ningún lugar.", selectedLocation: "Ubicación seleccionada", manualCoordinates: "Introducir coordenadas manualmente", geocodingCredit: "Datos de búsqueda © colaboradores de OpenStreetMap · Photon", footerTagline: "Tu vida de buceo, en todas partes.", mobileApps: "Aplicaciones móviles", iosApp: "Descargar para iOS", androidApp: "Disponible en Android", comingSoon: "Próximamente", footerRights: "Todos los derechos reservados.", deleteDive: "Eliminar inmersión", deleteDiveConfirm: "¿Eliminar esta entrada del diario y sus fotos?", groupDive: "Agrupar inmersiones", groupSize: "Número de inmersiones idénticas", clickDiveActions: "Haz clic o clic derecho en una entrada para agruparla o eliminarla.", mapFilters: "Filtros de visualización del mapa", startDate: "Fecha de inicio", endDate: "Fecha de fin", invalidDateRange: "Elige un intervalo válido que empiece hoy o después.", profileDiveMap: "Mapa de inmersiones", profileDiveMapSub: "Lugares donde este buceador ha explorado el mundo submarino.", noMappedDives: "Aún no hay inmersiones públicas geolocalizadas.", clickReviewDetails: "Haz clic en una reseña para ver su mapa y fotos.", reviewDetails: "Ubicación y fotos del sitio", close: "Cerrar", friendActivity: "Inmersiones y planes de amigos",
  },
} as const;

export type FeatureKey = keyof typeof copy.en;
export function featureCopy(locale: Locale) { return copy[locale]; }
