import React, { useCallback, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useFocusEffect, useNavigation } from "@react-navigation/native";
import { api } from "../api";
import { useLanguage } from "../i18n";
import { colors } from "../theme";
import type { Site } from "../types";
import { Button, Card, Field, Notice, Screen, SectionTitle, Title } from "../ui";

type AdminUser = { id: string; publicId: string; username: string; firstName: string; lastName: string; email: string; role: string; profileVisibility: string; logbookVisibility: string; createdAt: string; _count: { dives: number; plannedDives: number; reviews: number } };
type Log = { id: string; action: string; createdAt: string; actor?: { username: string } | null; site?: { name: string } | null };
type AdminSite = Site & { name: string; source: string; reviewCount: number; description?: string | null };

export function AdminScreen() {
  const { t } = useLanguage(); const navigation = useNavigation<any>(); const [tab, setTab] = useState<"users" | "sites">("users"); const [users, setUsers] = useState<AdminUser[]>([]); const [sites, setSites] = useState<AdminSite[]>([]); const [logs, setLogs] = useState<Log[]>([]); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<AdminSite | null>(null); const [form, setForm] = useState({ name: "", latitude: "", longitude: "", description: "", targetId: "" }); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { if (tab === "users") setUsers((await api<{ users: AdminUser[] }>(`/api/admin/users?q=${encodeURIComponent(query)}`)).users); else { const result = await api<{ sites: AdminSite[]; logs: Log[] }>(`/api/admin/sites?q=${encodeURIComponent(query)}`); setSites(result.sites); setLogs(result.logs); } } catch { setMessage(t("error")); } }, [query, t, tab]); useFocusEffect(useCallback(() => { void load(); }, [load]));
  function select(site: AdminSite) { setSelected(site); setForm({ name: site.name, latitude: String(site.latitude), longitude: String(site.longitude), description: site.description || "", targetId: "" }); }
  async function update() { if (!selected) return; try { await api(`/api/admin/sites/${selected.id}`, { method: "PATCH", body: JSON.stringify({ name: form.name, latitude: Number(form.latitude), longitude: Number(form.longitude), description: form.description }) }); setSelected(null); setMessage(t("saved")); await load(); } catch { setMessage(t("error")); } }
  function remove() { if (!selected) return; Alert.alert(t("delete"), t("confirmDelete"), [{ text: t("cancel"), style: "cancel" }, { text: t("delete"), style: "destructive", onPress: () => void api(`/api/admin/sites/${selected.id}`, { method: "DELETE" }).then(() => { setSelected(null); return load(); }).catch(() => setMessage(t("error"))) }]); }
  async function merge() { if (!selected || !form.targetId) return; try { await api("/api/admin/sites/merge", { method: "POST", body: JSON.stringify({ duplicateId: selected.id, targetId: form.targetId.trim() }) }); setSelected(null); await load(); } catch { setMessage(t("error")); } }
  return <Screen><Title title={t("adminTitle")} subtitle="BlueMates operations" /><View style={styles.tabs}><View style={styles.half}><Button title={t("users")} onPress={() => setTab("users")} variant={tab === "users" ? "primary" : "secondary"} /></View><View style={styles.half}><Button title={t("sites")} onPress={() => setTab("sites")} variant={tab === "sites" ? "primary" : "secondary"} /></View></View><Card><Field label={t("search")} value={query} onChangeText={setQuery} /><Button title={t("search")} onPress={() => void load()} variant="secondary" /></Card>{message ? <Notice text={message} error={message === t("error")} /> : null}
    {tab === "users" ? <><SectionTitle count={users.length}>{t("users")}</SectionTitle>{users.map((user) => <Pressable key={user.id} onPress={() => navigation.navigate("PublicProfile", { publicId: user.publicId })}><Card><Text style={styles.name}>{user.firstName} {user.lastName} · @{user.username}</Text><Text style={styles.meta}>{user.email} · {user.publicId} · {user.role}</Text><Text style={styles.counts}>{user._count.dives} {t("completed")} · {user._count.plannedDives} {t("upcoming")} · {user._count.reviews} {t("reviewCount")}</Text></Card></Pressable>)}</> : <><SectionTitle count={sites.length}>{t("sites")}</SectionTitle>{selected ? <Card><Field label={t("siteName")} value={form.name} onChangeText={(value) => setForm({ ...form, name: value })} /><View style={styles.tabs}><View style={styles.half}><Field label="Latitude" value={form.latitude} onChangeText={(value) => setForm({ ...form, latitude: value })} keyboardType="decimal-pad" /></View><View style={styles.half}><Field label="Longitude" value={form.longitude} onChangeText={(value) => setForm({ ...form, longitude: value })} keyboardType="decimal-pad" /></View></View><Field label={t("details")} value={form.description} onChangeText={(value) => setForm({ ...form, description: value })} multiline /><Button title={t("save")} onPress={() => void update()} /><Field label="Target site UUID" value={form.targetId} onChangeText={(value) => setForm({ ...form, targetId: value })} autoCapitalize="none" /><Button title="Merge duplicate into target" onPress={() => void merge()} variant="danger" /><Button title={t("delete")} onPress={remove} variant="danger" /><Button title={t("cancel")} onPress={() => setSelected(null)} variant="secondary" /></Card> : null}{sites.map((site) => <Pressable key={site.id} onPress={() => select(site)}><Card><Text style={styles.name}>{site.name}</Text><Text style={styles.meta}>{site.source} · {site.latitude.toFixed(4)}, {site.longitude.toFixed(4)}</Text><Text style={styles.counts}>{site.reviewCount} {t("reviewCount")} · {site.id}</Text></Card></Pressable>)}<SectionTitle count={logs.length}>{t("changeLog")}</SectionTitle>{logs.map((log) => <Card key={log.id}><Text style={styles.name}>{log.action} · {log.site?.name || "—"}</Text><Text style={styles.meta}>@{log.actor?.username || "system"} · {new Date(log.createdAt).toLocaleString()}</Text></Card>)}</>}
  </Screen>;
}

const styles = StyleSheet.create({ tabs: { flexDirection: "row", gap: 9 }, half: { flex: 1 }, name: { color: colors.text, fontWeight: "900", fontSize: 16 }, meta: { color: colors.muted, fontSize: 12 }, counts: { color: colors.blue, fontWeight: "800", fontSize: 12 } });
