import React, { useCallback, useEffect, useState } from "react";
import { Image, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { useFocusEffect, useNavigation } from "@react-navigation/native";
import { ApiError, api, mediaSource, uploadImage } from "../api";
import { useLanguage } from "../i18n";
import { LocationPicker, SelectedPlace } from "../LocationPicker";
import { PhotoPicker } from "../PhotoPicker";
import { colors } from "../theme";
import type { Review, Site } from "../types";
import { Button, Card, Field, Notice, Screen, SectionTitle, Title } from "../ui";

type Candidate = Site & { name: string; distanceMeters: number | null; nameSimilarity: number; reviewCount: number };

export function ReviewsScreen() {
  const { t } = useLanguage(); const navigation = useNavigation<any>(); const [reviews, setReviews] = useState<Review[]>([]); const [refreshing, setRefreshing] = useState(false); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const [siteName, setSiteName] = useState(""); const [selectedSite, setSelectedSite] = useState<Candidate | null>(null); const [place, setPlace] = useState<SelectedPlace | null>(null); const [rating, setRating] = useState(5); const [comment, setComment] = useState(""); const [photos, setPhotos] = useState<string[]>([]); const [uploadedPhotoIds, setUploadedPhotoIds] = useState<string[]>([]); const [candidates, setCandidates] = useState<Candidate[]>([]); const [confirmNew, setConfirmNew] = useState(false);
  const load = useCallback(async () => { try { setReviews((await api<{ reviews: Review[] }>("/api/reviews")).reviews); } finally { setRefreshing(false); } }, []); useFocusEffect(useCallback(() => { void load(); }, [load]));
  useEffect(() => { if (siteName.trim().length < 2 || selectedSite) { setCandidates([]); return; } const timer = setTimeout(() => { const coords = place ? `&lat=${place.latitude}&lon=${place.longitude}` : ""; void api<{ sites: Candidate[] }>(`/api/sites/candidates?name=${encodeURIComponent(siteName.trim())}${coords}`).then((result) => setCandidates(result.sites)).catch(() => undefined); }, 400); return () => clearTimeout(timer); }, [place, selectedSite, siteName]);
  function choose(site: Candidate) { setSelectedSite(site); setSiteName(site.name); setPlace({ name: site.name, latitude: site.latitude, longitude: site.longitude }); setCandidates([]); setConfirmNew(false); }
  function reset() { setSiteName(""); setSelectedSite(null); setPlace(null); setRating(5); setComment(""); setPhotos([]); setUploadedPhotoIds([]); setCandidates([]); setConfirmNew(false); }
  async function publish(force = false) {
    if (!siteName.trim() || (!selectedSite && !place)) return setMessage(t("error")); setBusy(true); setMessage("");
    try { const photoIds = uploadedPhotoIds.length ? uploadedPhotoIds : (await Promise.all(photos.map((uri) => uploadImage(uri, "REVIEW")))).map((item) => item.media.id); if (!uploadedPhotoIds.length) setUploadedPhotoIds(photoIds); const body = selectedSite ? { siteId: selectedSite.id, rating, comment, photoIds } : { siteName: siteName.trim(), latitude: place!.latitude, longitude: place!.longitude, rating, comment, photoIds, confirmNewSite: force }; await api("/api/reviews", { method: "POST", body: JSON.stringify(body) }); reset(); setOpen(false); setMessage(t("created")); await load();
    } catch (cause) { if (cause instanceof ApiError && cause.code === "POSSIBLE_DUPLICATE") { const details = cause.details as { sites?: Candidate[] }; setCandidates(details.sites || []); setConfirmNew(true); } else setMessage(t("error")); } finally { setBusy(false); }
  }
  return <Screen refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} tintColor={colors.aqua} />}>
    <Title title={t("reviewTitle")} subtitle={t("reviewSub")} /><Button title={open ? t("cancel") : `＋ ${t("add")}`} onPress={() => setOpen(!open)} variant={open ? "secondary" : "primary"} />
    {open ? <Card><Field label={t("siteName")} value={siteName} onChangeText={(value) => { setSiteName(value); setSelectedSite(null); setConfirmNew(false); }} />{selectedSite ? <Notice text={`✓ ${t("existingSite")}: ${selectedSite.name}`} /> : null}<LocationPicker value={place} onChange={(value) => { setPlace(value); setSelectedSite(null); if (!siteName) setSiteName(value.name); }} />
      {candidates.length ? <View style={styles.candidates}><Text style={styles.warning}>{confirmNew ? t("duplicate") : t("nearby")}</Text>{candidates.map((site) => <Pressable key={site.id} style={styles.candidate} onPress={() => choose(site)}><View style={styles.grow}><Text style={styles.site}>{site.name}</Text><Text style={styles.meta}>{site.distanceMeters != null ? `${site.distanceMeters} m` : `${Math.round(site.nameSimilarity * 100)}%`} · {site.reviewCount} {t("reviewCount")}</Text></View><Text style={styles.choose}>＋</Text></Pressable>)}</View> : null}
      <Text style={styles.label}>{t("rating")}</Text><View style={styles.stars}>{[1, 2, 3, 4, 5].map((value) => <Pressable key={value} onPress={() => setRating(value)}><Text style={[styles.star, value > rating && styles.starOff]}>★</Text></Pressable>)}</View><Field label={t("comment")} value={comment} onChangeText={setComment} multiline /><PhotoPicker uris={photos} onChange={(value) => { setPhotos(value); setUploadedPhotoIds([]); }} /><Button title={busy ? t("loading") : t("publish")} onPress={() => void publish(false)} disabled={busy} />{confirmNew ? <Button title={t("createAnyway")} onPress={() => void publish(true)} disabled={busy} variant="danger" /> : null}</Card> : null}
    {message ? <Notice text={message} error={message === t("error")} /> : null}<SectionTitle count={reviews.length}>{t("reviews")}</SectionTitle>{!reviews.length ? <Card><Text style={styles.empty}>{t("noReviews")}</Text></Card> : reviews.map((review) => <Pressable key={review.id} onPress={() => review.site?.id && navigation.navigate("SiteDetail", { siteId: review.site.id })}><Card><Text style={styles.site}>{review.siteName}</Text><Text style={styles.starsText}>{"★".repeat(review.rating)}</Text>{review.comment ? <Text style={styles.comment}>{review.comment}</Text> : null}<Text style={styles.meta}>{review.latitude.toFixed(5)}, {review.longitude.toFixed(5)}</Text>{review.photos.length ? <View style={styles.photos}>{review.photos.map((photo) => <Image key={photo.id} source={mediaSource(`/api/media/${photo.id}`)} style={styles.photo} />)}</View> : null}</Card></Pressable>)}
  </Screen>;
}

const styles = StyleSheet.create({ label: { color: colors.text, fontWeight: "800" }, stars: { flexDirection: "row", gap: 5 }, star: { color: "#e3ad00", fontSize: 34 }, starOff: { color: "#cbd7dc" }, candidates: { gap: 8, backgroundColor: "#fff8df", borderRadius: 13, padding: 10 }, warning: { color: "#785c00", fontWeight: "800" }, candidate: { flexDirection: "row", alignItems: "center", backgroundColor: "white", borderRadius: 11, padding: 10, borderWidth: 1, borderColor: "#edda99" }, grow: { flex: 1 }, site: { color: colors.text, fontSize: 17, fontWeight: "900" }, meta: { color: colors.muted, fontSize: 12, marginTop: 3 }, choose: { color: colors.blue, fontSize: 24, fontWeight: "900" }, starsText: { color: "#e3ad00", fontSize: 20 }, comment: { color: colors.text, lineHeight: 20 }, empty: { color: colors.muted, textAlign: "center" }, photos: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, photo: { width: 78, height: 78, borderRadius: 11 } });
